### PR TITLE
Follow up of PR691

### PR DESCRIPTION
**Pull request by tcsabina**

### CODE REVIEW

**Comment by VVD** [comment]
Look like use before initialization.

**Comment by tcsabina** [comment]
@ciscon @dsvensson , how does this PR look like? Does it tackle all the issues from PR 691?

@VVD , where exactly?

**Comment by dsvensson** [comment]
Particle trails no longer render when fog is enabled, haven't checked other particle effects so maybe more affected. Haven't had time to check why, and it's slightly outside of my skill set. Maybe it's just some shader ordering or something. At the same time it would suck if the fog stuff bitrotted unmerged as it looks great otherwise.

**Comment by dsvensson** [comment]
The texture commit can be merged separately if you put this on hold, it works great.

**Pull request merged**
