### PR TITLE
The latest works of the Master

### PR DESCRIPTION
**Pull request by tcsabina**

### CODE REVIEW

**Comment by ciscon** [comment]
r_fx_fog throws glsl compilation errors and drops my framerate quite a bit

VertexShader.Compile(aliasmodel[0]) failed
Shader->Compile(8B31) failed
-- Version: 4.6 (Compatibility Profile) Mesa 22.2.0
--    GLSL: 4.60
0:201(20): error: illegal use of reserved word `input'
0:201(20): error: syntax error, unexpected ERROR_TOK, expecting ')'

VertexShader.Compile(aliasmodel[0]) failed

**Comment by dsvensson** [comment]
...and this fixes loading fog color from maps
```
diff --git a/r_rmisc.c b/r_rmisc.c
index 04dbf54b..05682bcd 100644
--- a/r_rmisc.c
+++ b/r_rmisc.c
@@ -192,9 +192,9 @@ static qbool R_ParseWorldspawn(const char* entstring, worldspawn_info_t* worldsp
 			Cmd_TokenizeStringEx(&fog, temp);
 			if (Cmd_ArgcEx(&fog) == 4) {
 				worldspawn->fog_density = atof(Cmd_ArgvEx(&fog, 0));
-				worldspawn->fog_color[0] = atof(Cmd_ArgvEx(&fog, 0));
-				worldspawn->fog_color[1] = atof(Cmd_ArgvEx(&fog, 1));
-				worldspawn->fog_color[2] = atof(Cmd_ArgvEx(&fog, 2));
+				worldspawn->fog_color[0] = atof(Cmd_ArgvEx(&fog, 1));
+				worldspawn->fog_color[1] = atof(Cmd_ArgvEx(&fog, 2));
+				worldspawn->fog_color[2] = atof(Cmd_ArgvEx(&fog, 3));
 
 				worldspawn->fog_density = bound(0, worldspawn->fog_density, 1);
 				worldspawn->fog_color[0] = bound(0, worldspawn->fog_color[0], 1);
```

**Comment by dsvensson** [comment]
All rockettrails except blood are (4, 5) not drawn, haven't checked other particle effects.

**Comment by tcsabina** [comment]
@ciscon @dsvensson, you patches are part of #692, as I was not able to update this PR.

**Comment by tcsabina** [comment]
This PR is closed, as the follow-up PR (700) will be merged. That one contains some patches on top of this.

**Pull request closed without merging**
