### PR TITLE
add r_sgbloodColor

### PR DESCRIPTION
**Pull request by krizej**
requested on the quakeworld discord [here](https://discord.com/channels/166866762787192833/179895022366228481/1134763771374604350)

### CODE REVIEW

**Comment by tcsabina** [comment]
Hi @krizej,
So we have now a new setting, called r_sgbloodColor, right?
Could you add a little helper text to help_variables.json about it?

**Comment by krizej** [comment]
did i not?

**Comment by tcsabina** [comment]
> did i not?

Hmm, I might be blind...
I only see the update for the 'r_lgbloodColor' variable in there. But I don't see anything there for 'r_sgbloodColor'...

**Comment by tcsabina** [comment]
Yes, I am blind. It is just above it...
And I even wear my glasses while I type....

Sorry dude!

**Comment by krizej** [comment]
hehe no worries!

**Pull request merged**
