### PR TITLE
Add bindedit command

### PR DESCRIPTION
**Pull request by krizej**
requested in #739

### CODE REVIEW

**Comment by tcsabina** [comment]
Hi @krizej ,

Thank you for the contribution!

Could you also add a short entry in the `help_commands.json` file, which is the 'in-built' help of ezquake?

**Comment by tcsabina** [comment]
@krizej,
Are you willing to update this PR with the requested change?

**Comment by krizej** [comment]
hi, do you mean the description of the command? i have already done that

**Comment by tcsabina** [comment]
> hi, do you mean the description of the command? i have already done that

No, I mean the move of the variable definitions ;)

**Comment by krizej** [comment]
hmm i dont see anything like that.

**Comment by tcsabina** [comment]
> hmm i dont see anything like that.

You don't see this in the PR? :
image

**Comment by krizej** [comment]
i do not

**Comment by ciscon** [comment]
https://github.com/QW-Group/ezquake-source/pull/769/files

**Pull request merged**
