### PR TITLE
BUILD: Vcpkg instead of vendored binary blobs in the repo.

### PR DESCRIPTION
**Pull request by dsvensson**
Initial testing looks fine, CI build time with a warm cache is fine. Will put an end to the repository bloat, and make it easier to update, or introduce new libraries in the future. Will fit even better into a cmake build when that time comes. The latter could also enable reproducible builds on Linux as well if opting to produce a static binary there with known dependency versions. 

In interesting part about the current checked in blobs is that some of them have a 'd' suffix, which may mean they are debug builds, so that would be an improvement as well.

 #817 

Also relevant to #816 PR.

### CODE REVIEW

**Comment by dsvensson** [comment]
Ah look at that, the non-Windows build used the repo version of minizip. Could restore those source files, or change those builds to prefer OS version instead. Up for discussion.

**Comment by ciscon** [comment]
that's why i mentioned the makefile/dep/script stuff, that just needs to be changed real quick - though it looks like all the builds fail.

**Comment by dsvensson** [comment]
The windows build failing here is because it lacks my custom github actions manifest, build succeeds in my repo. Just wanted to share the state of things.

**Comment by dsvensson** [comment]
Oh right, there was the GL header stuff on macOS left. Hopefully just include path issue, otherwise it's fairly harmless to ressurect those header files.

**Comment by dsvensson** [comment]
Turns out SDL exposes wrapper headers for OpenGL that works on all platforms, so switched to that.

**Comment by dsvensson** [comment]
Due to the above OpenGL finding I suspect the vcpkg.json should no longer have to require the opengl stuff. Will try building without tonight.

**Pull request merged**
