### PR TITLE
illumos build fix proposal.

### PR DESCRIPTION
**Pull request by devnexen**
also renaming few types to avoid conflicts with existing ones.

### CODE REVIEW

**Comment by tcsabina** [comment]
Hi @devnexen 
I am not so happy about this, to be honest.
`dir_t` and `file_t` are also used in an other project (mvdsv), so if we want to rename them here, we should do it for consistency in the other project as well.
Does this illumos thingy really brings us dir_t and file_t typedefs? Our linux users don't complain that they cannot compile, so it must be something specific to this specific distro...

**Comment by devnexen** [comment]
yes it s specific to this system.

**Comment by dsvensson** [comment]
Pretty common practice to prefix all project types due to the lack of namespace in C, nothing weird here, other than mvdsv not being a lilbmvdsv.a input to the build?

**Comment by tcsabina** [comment]
> Pretty common practice to prefix all project types due to the lack of namespace in C, nothing weird here...

I am still not convinced that the proposed change worth it.
Currently if you work on the QW API (the protocol between server and client), it is pretty easy to find the link between the mvdsv and ezquake project, because of these shared typedefs.
Renaming them in one project and not in the other, just for the sake of a random linux distribution, is a no-go in my opinion. It just doesn't worth the effort.

I must admit that these typedefs should go into some shared repo instead of them being defined and used in both projects separately, but we are not there yet.

But let this be not my own decision.
@qqshka, if you have some time, could you take a look on this? What do you think?

**Comment by danielstravito** [comment]
It's not Linux, it's a Solaris derivative, before you know it there's Haiku and Tru64 PR's all over the place :)

**Comment by dsvensson** [comment]
It's not Linux, it's a Solaris derivative, before you know it there's Haiku and Tru64 PR's all over the place :)

**Comment by tcsabina** [comment]
after an internal discussion we have decided not to merge this PR.

**Pull request closed without merging**
