### PR TITLE
BINDS: default weapon next/prev binds using weapon command instead of…

### PR DESCRIPTION
**Pull request by ciscon**
… impulse which interferes with weapon preselection.  changing to impulse.

### CODE REVIEW

**Comment by meag** [comment]
Hi ciscon

What script combination is this fixing?  It breaks my weaponscript for example, and the change from impulse to weapon was made because people were complaining in the other direction.

meag

**Comment by tcsabina** [comment]
@ciscon ,

What's up with this one?

**Comment by ciscon** [comment]
this was an old thing someone reported, using prev/next weapon binds calls weapon X instead of impulse, thereby replacing the previous weapon preselection priority list instead of just affecting what the next +attack would be.  if @meag had a reason to switch it to this then it's probably going to upset someone one way or the other.

**Comment by tcsabina** [comment]
> this was an old thing someone reported, using prev/next weapon binds calls weapon X instead of impulse, thereby replacing the previous weapon preselection priority list instead of just affecting what the next +attack would be. if @meag had a reason to switch it to this then it's probably going to upset someone one way or the other.

So leave it as it is? Meaning to close the PR without merge?

**Pull request closed without merging**
